version: '3.8'
services:

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            -   .:/app
        depends_on:
            -   db

    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: admin
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: Nuriknurik1228337!
        volumes:
            -   ./storage/dbdata:/var/lib/mysql
        ports:
            - "33066:3306"
